### ISSUE TITLE
Reward distribution for Hunt Grant contracts community audit 💸

### ISSUE THREAD

**Issue by sebayaki** [Steemhunt/hunt-town#11]
| Username           | Address                                  | Points |
|--------------------|------------------------------------------|--------|
| @bugs-we           | 0x463470955C61a54210b5dDcc20847cC325A2FF38 | +5     |
| @Bookahh           | 0xff88430C7c656fC6355656234bc522B8c7E03B40 | +1     |
| @Tisi22            | 0xf2CF408Df63125A63e1ba2CdD3c39370E7652ba9 | +1     |
| @MrKevinOConnell    | 0x69689f02c4154B049Fb42761ef8fA00808f1B7Ea | +10    |
| @stuckinaboot      | 0xcf75Bf188c5CA5198eF571aed3D75ECDe3bcD9D9                                  | +10    |
| @Desperado-nerd    | 0x6c9a51aa8a994CFeEB27D7b94df43Ab1f05aCeDc | +5     |
| @dalechyn          | 0x7389Ec4FB686a16966f2975758e9F1B8345f5e63 | +1     |
| @ruhul0       | 0x14cEe93be114986C609F907C16de143938B0D403 | +5     |
| @T-Damer      | 0x6c9e4f9e8ca34743c3926131dff919bd9d934c9e | +10    |
| @ryanjshaw         | 0x262d9290e5924bf587844fb522131fb62932bb5e | +50    |

Basic principle for distributions:

- +1 Everyone who participated, even if with just "LGTM" or invalid comments
- +5 Valid contributions, but not fixed due to a design choice
- +10 Vadlid contributions, and the fixes applied

@stuckinaboot @ruhul0 @T-Damer @ryanjshaw 👉🏻 Please leave your public wallet address here for receiving the bounty.

The bounties are Mini Building NFTs, backed by 100 HUNT tokens.
You can trade them directly on the bonding curve: https://mint.club/nft/base/MINIBD

Thank you so much for your participation, and have a great weekend! 😄

**Comment by exitLQ** [comment]
thanks, have a nice weekend!

**Comment by ruhul0** [comment]
0x14cEe93be114986C609F907C16de143938B0D403
Here it is

**Comment by ryanjshaw** [comment]
Awesome - glad I could help!

0x262d9290e5924bf587844fb522131fb62932bb5e

**Comment by Bookahh** [comment]
Thank you👏

**Comment by stuckinaboot** [comment]
Here’s my wallet address: 0xcf75Bf188c5CA5198eF571aed3D75ECDe3bcD9D9

nice job with this!

**Comment by T-Damer** [comment]
0x6c9e4f9e8ca34743c3926131dff919bd9d934c9e

Thanks :)
Good job out there 🚀

**Comment by sebayaki** [comment]
@bugs-we @Bookahh @Tisi22 @MrKevinOConnell @stuckinaboot @Desperado-nerd @dalechyn @ruhul0 @T-Damer @ryanjshaw

[Mini Building](https://mint.club/nft/base/MINIBD) rewards have been sent to the wallets! 
Bulk TX: https://basescan.org/tx/0x601c084bcb07d587c7305cd0ab354346bcd7b1848dfa29226d39e7cc1f09e592

With the Mini Building rewards, you can:
1. Participate in $hunt tipping on [Warpcast](https://warpcast.com/~/channel/hunt). Your allowance will be increased automatically from tomorrow (UTC 0) if your wallet is connected to your Warpcast account.
2. If you verify your building NFTs on our [Discord](https://discord.gg/hunt-town) in the #verify-building channel, you can also get daily BUILD points. You can use these points to access many useful builder tools on our Discord and purchase a weekly raffle ticket for a Building NFT.

Thank you again for your participations and I hope to see you guys around in Hunt Town near future :)

**Comment by ryanjshaw** [comment]
> If you verify your building NFTs on our [Discord](https://discord.gg/hunt-town) in the #verify-building channel, you can also get daily BUILD points. You can use these points to access many useful builder tools on our Discord and purchase a weekly raffle ticket for a Building NFT.

Didn't know this. Done!
